name: Lint and Compile CDK

on:
  push:
    branches: [main]
  pull_request:

defaults:
  run:
    shell: bash
    working-directory: infrastructure

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install deps
        run: yarn install --frozen-lockfile

      - run: yarn lint
      - run: yarn prettier
      - run: yarn compile
      - run: yarn synth
      - run: yarn test
